### ISSUE TITLE
Typos in /menu

### ISSUE THREAD

**Issue by ribbette** [MCAdventureCraft/Server#10]
**Describe the bug**
Two typos on words

**To Reproduce**
**first typo**
type /menu in chat
hover over %reputation%username

**second typo**
type /menu in chat
click %reputation%username
hover over the leather tunic

**Expected behavior**
"enhacements" should read enhancements 
"consmetics" should read cosmetics

**Screenshots**
![2023-12-11_17 05 33](https://github.com/MCAdventureCraft/Server/assets/153310209/3e8befdf-d354-4aa6-b688-019207b25da0)
![2023-12-11_17 05 50](https://github.com/MCAdventureCraft/Server/assets/153310209/c805756a-6d5c-49a2-b6b1-c8d5ac79ff9c)

**Minecraft (please complete the following information):**
 - Version: 1.20.2
 - 3rd Party Version Fabric 1.20.2
 - 3rd Party Client N/A
**Additional context**
N/A

**Comment by MCAdventureCraft** [comment]
thank you for your report! Has been fixed :)
