### ISSUE TITLE
Not working commands

### ISSUE THREAD

**Issue by phi-del** [MCAdventureCraft/Server#14]
The commands bellyflop crawl spin and lay dont work

**To Reproduce**

1. Type the command in chat like /crawl

**Expected behavior**
That bellyflop lets you make a bellyflop

**Minecraft (please complete the following information):**
 - Version: 1.20.2
 - 3rd Party Version fabric 1.20.2
 

**Additional context**

**Comment by MCAdventureCraft** [comment]
has been fixed, thank you for the report
