### ISSUE TITLE
Duplicate Server Messages

### ISSUE THREAD

**Issue by ribbette** [MCAdventureCraft/Server#5]
**Describe the bug**
In-Game chat messages are being duplicated.

**To Reproduce**
Send a message in game

**Expected behavior**
Non duplicated messages

**Screenshots**
![Capture](https://github.com/MCAdventureCraft/Server/assets/153310209/99206787-a29f-496c-8a21-afb30b6b2543)

**Minecraft (please complete the following information):**
 - Version: 1.20.2
 - 3rd Party Version Fabric
 - 3rd Party Client N/A

**Additional context**
It is happening for the other players in game, not just myself.

**Comment by MCAdventureCraft** [comment]
thanks for the report. has been fixed.
