### ISSUE TITLE
elytra combat log

### ISSUE THREAD

**Issue by plex1108** [MCAdventureCraft/Server#7]
**Describe the bug**
Flying and hitting a block with an elytra triggers combat log.

**To Reproduce**
1. Equip an elytra
2. Fly
3. Hit a block

**Expected behavior**
no combat log

**Screenshots**

**Minecraft (please complete the following information):**
 - Version: [e.g. 1.20.1]
 - 3rd Party Version [e.g. Optifine 1.20.1]
 - 3rd Party Client [e.g. Lunar Client]

**Additional context**

**Comment by MCAdventureCraft** [comment]
has been patched.
